jasypt:
  encryptor:
    password: something
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    algorithm: PBEWithMD5AndDES

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sportsgeekdb
    username: ENC(ZfEntFj2ODzaAPMVfbgBAg==)
    password: ENC(WsfbYQWB5LzsrAQ0ZtrZlw==)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: matches-ms

server:
  port: 8081
  error:
    include-stacktrace: never
#    whitelabel:
#      enabled: false

matchidYaml: There is no match with matchId = %d

debug: true

invalidPath: you have entered invalid path in address bar
notFoundError: 404
sucessful: 200
created: 201
deletedResponse: match with matchId = %d deleted sucessfully
insertedResponse: match with matchId = %d inserted sucessfully
